dockerfile: add missing mount completions
Now users will get suggestions for misspelled "destination" and "size"
mount options:

    ERROR: failed to solve: unexpected key 'destinationn' in 'destinationn=/lol' (did you mean destination?)
    ERROR: failed to solve: unexpected key 'sizee' in 'sizee=1024' (did you mean size?)

Signed-off-by: Arkadiusz Drabczyk <arkadiusz@drabczyk.org>