util/archutil: re-generate to fix validation for mips64
validation was failing; not sure what introduced it though;

     > [validate 1/1] RUN --mount=type=bind,target=.,rw     --mount=type=bind,from=generate,source=/out,target=/generated-files <<EOT (set -e...):
    0.379 ERROR: The result of archutil differs. Please update with "make archutil"
    0.379  M util/archutil/mips64_binary.go
    0.379  M util/archutil/mips64le_binary.go
    ------
    archutil.Dockerfile:116
    --------------------
     115 |     FROM base AS validate
     116 | >>> RUN --mount=type=bind,target=.,rw \
     117 | >>>     --mount=type=bind,from=generate,source=/out,target=/generated-files <<EOT
     118 | >>>   set -e
     119 | >>>   git add -A
     120 | >>>   if [ "$(ls -A /generated-files)" ]; then
     121 | >>>     cp -rf /generated-files/* ./util/archutil
     122 | >>>   fi
     123 | >>>   diff=$(git status --porcelain -- util/archutil)
     124 | >>>   if [ -n "$diff" ]; then
     125 | >>>     echo >&2 'ERROR: The result of archutil differs. Please update with "make archutil"'
     126 | >>>     echo "$diff"
     127 | >>>     exit 1
     128 | >>>   fi
     129 | >>> EOT
     130 |
    --------------------
    ERROR: failed to solve: process "/bin/sh -c   set -e\n  git add -A\n  if [ \"$(ls -A /generated-files)\" ]; then\n    cp -rf /generated-files/* ./util/archutil\n  fi\n  diff=$(git status --porcelain -- util/archutil)\n  if [ -n \"$diff\" ]; then\n    echo >&2 'ERROR: The result of archutil differs. Please update with \"make archutil\"'\n    echo \"$diff\"\n    exit 1\n  fi\n" did not complete successfully: exit code: 1

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>