[0.8] skip TestIntegration/TestStargzLazyPull
It's failing on go1.18 bullseye, and this branch is only used for vendoring in
moby/moby, which doesn't use this.

```
=== CONT  TestIntegration/TestStargzLazyPull/worker=containerd-snapshotter-stargz
    client_test.go:2158:
        	Error Trace:	client_test.go:2158
        	            				run.go:171
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = executor failed running [/bin/touch /foo]: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/tmp/bktest_buildkitd4012827731/containerd-stargz/resolv.conf" to rootfs at "/tmp/bktest_containerd3597200052/state/io.containerd.runtime.v2.task/buildkit/h77dkpz3tip7tkyazfjvvoyug/rootfs/etc/resolv.conf" caused: open /tmp/bktest_containerd3597200052/state/io.containerd.runtime.v2.task/buildkit/h77dkpz3tip7tkyazfjvvoyug/rootfs/etc/resolv.conf: function not implemented: unknown
        	            	github.com/moby/buildkit/util/stack.Enable
        	            		/src/util/stack/stack.go:77
        	            	github.com/moby/buildkit/util/grpcerrors.FromGRPC
        	            		/src/util/grpcerrors/grpcerrors.go:188
        	            	github.com/moby/buildkit/util/grpcerrors.UnaryClientInterceptor
        	            		/src/util/grpcerrors/intercept.go:41
        	            	google.golang.org/grpc.(*ClientConn).Invoke
        	            		/src/vendor/google.golang.org/grpc/call.go:35
        	            	github.com/moby/buildkit/api/services/control.(*controlClient).Solve
        	            		/src/api/services/control/control.pb.go:1321
        	            	github.com/moby/buildkit/client.(*Client).solve.func2
        	            		/src/client/solve.go:201
        	            	golang.org/x/sync/errgroup.(*Group).Go.func1
        	            		/src/vendor/golang.org/x/sync/errgroup/errgroup.go:57
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1571
        	            	failed to solve
        	            	github.com/moby/buildkit/client.(*Client).solve.func2
        	            		/src/client/solve.go:214
        	            	golang.org/x/sync/errgroup.(*Group).Go.func1
        	            		/src/vendor/golang.org/x/sync/errgroup/errgroup.go:57
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1571
        	Test:       	TestIntegration/TestStargzLazyPull/worker=containerd-snapshotter-stargz
    run.go:166:
        	Error Trace:	run.go:166
        	            				panic.go:482
        	            				testing.go:864
        	            				client_test.go:2158
        	            				run.go:171
        	Error:      	Received unexpected error:
        	            	openfdat /tmp/bktest_containerd_stargz_grpc2440934492/root/snapshotter/snapshots/1/fs: transport endpoint is not connected
        	Test:       	TestIntegration/TestStargzLazyPull/worker=containerd-snapshotter-stargz
```

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>