[0.8] TestClientGatewayIntegration/TestClientGatewayExecError on stargz
It's failing on go1.18 bullseye, and this branch is only used for vendoring in
moby/moby, which doesn't use this.

```
=== CONT  TestClientGatewayIntegration/TestClientGatewayExecError/worker=containerd-snapshotter-stargz/rootfs_and_readwrite_scratch_mount
    build_test.go:1215:
        	Error Trace:	build_test.go:1215
        	Error:      	Not equal:
        	            	expected: "7lm22fjwmcq5lhh70drzvtqjc"
        	            	actual  : ""
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-7lm22fjwmcq5lhh70drzvtqjc
        	            	+
        	Test:       	TestClientGatewayIntegration/TestClientGatewayExecError/worker=containerd-snapshotter-stargz/rootfs_and_readwrite_scratch_mount
```

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>