[0.8] integration: skip TestSecurityModeSysfs (insecure mode)
This branch is only used for vendoring in moby/moby, which doesn't use this.

```
=== CONT  TestIntegration/TestSecurityModeSysfs/worker=oci/secmode=insecure
    client_test.go:685:
        	Error Trace:	client_test.go:685
        	            				run.go:171
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = executor failed running [mkdir /sys/fs/cgroup/securitytest]: exit code: 1
        	            	github.com/moby/buildkit/util/stack.Enable
        	            		/src/util/stack/stack.go:77
        	            	github.com/moby/buildkit/util/grpcerrors.FromGRPC
        	            		/src/util/grpcerrors/grpcerrors.go:188
        	            	github.com/moby/buildkit/util/grpcerrors.UnaryClientInterceptor
        	            		/src/util/grpcerrors/intercept.go:41
        	            	google.golang.org/grpc.(*ClientConn).Invoke
        	            		/src/vendor/google.golang.org/grpc/call.go:35
        	            	github.com/moby/buildkit/api/services/control.(*controlClient).Solve
        	            		/src/api/services/control/control.pb.go:1321
        	            	github.com/moby/buildkit/client.(*Client).solve.func2
        	            		/src/client/solve.go:201
        	            	golang.org/x/sync/errgroup.(*Group).Go.func1
        	            		/src/vendor/golang.org/x/sync/errgroup/errgroup.go:57
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1571
        	            	failed to solve
        	            	github.com/moby/buildkit/client.(*Client).solve.func2
        	            		/src/client/solve.go:214
        	            	golang.org/x/sync/errgroup.(*Group).Go.func1
        	            		/src/vendor/golang.org/x/sync/errgroup/errgroup.go:57
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1571
        	Test:       	TestIntegration/TestSecurityModeSysfs/worker=oci/secmode=insecure
...
...
    sandbox.go:223: time="2023-01-03T10:10:16Z" level=debug msg="> creating 501jemvwbacokctnpm9779p7y [mkdir /sys/fs/cgroup/securitytest]"
    sandbox.go:223: mkdir: can't create directory '/sys/fs/cgroup/securitytest': File exists
```

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>